### ISSUE TITLE
Downloading abf files?

### ISSUE THREAD

**Issue by pgleeson** [derekhoward/nwb_conversion#10]
@derekhoward Thanks for making these scripts avaiable. Apologies if I'm missing something, but many of the notebooks assume the raw data in abf files is available in /data/raw. Where can these be downloaded?

**Comment by derekhoward** [comment]
Hi @pgleeson the abf files can be downloaded from http://gigadb.org/dataset/view/id/102317

**Comment by pgleeson** [comment]
Thanks for that @derekhoward. Have found them, and have managed to run a number of the notebooks. 

Have been testing out the generated NWB files on NWB Explorer and they work nicely, e.g. http://nwbexplorer.opensourcebrain.org/nwbfile=https://dandiarchive.s3.amazonaws.com/blobs/00c/e6b/00ce6b6b-007e-4eff-9361-e68cd5f5846c
